apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  DB_HOST: {{ .Values.db.host | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
  DB_USER: {{ .Values.db.user | quote }}
  GCP_PROJECT: {{ .Values.project | quote }}
