apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lab-route
  namespace: default
spec:
  parentRefs:
    - name: lab-gateway
  {{- if .Values.domain }}
  hostnames:
    - {{ .Values.domain | quote }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: backend-svc
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend-svc
          port: 80
